---
title: "JohnCount18 Flash C"
author: "Yuxin Zou"
date: 2018-4-17
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```

```{r, echo=FALSE}
# TEMPORARY.
knitr::opts_chunk$set(eval = TRUE)
```

```{r packages}
library(flashr); library(colorRamps); library(corrplot); library(mashr)
```

Read Count 18 Ind Random data
```{r}
data = readRDS('../output/Count_IndRan_limmaBayes.rds')
# Time 18
Eighteen = grepl('t18', colnames(data$beta))

beta_class = data$beta[, Eighteen]
sebeta_class = data$sebeta[, Eighteen]
colnames(beta_class) = colnames(sebeta_class) = gsub( "\\..*$", "", colnames(beta_class))
```

# Flash on Z (C/Shat)

Set flash data object
```{r}
mash.data = mash_set_data(Bhat = beta_class, Shat = sebeta_class, df = data$df[1], alpha=1)
flash.data = flash_set_data(mash.data$Bhat)
flash.model = flash(flash.data, greedy=TRUE, backfit = TRUE)
```
```{r}
factors = flash_get_ldf(flash.model)$f
row.names(factors) = colnames(beta_class)
pve.order = order(flash_get_pve(flash.model), decreasing = TRUE)

par(mfrow=c(2,3))
for(i in pve.order){
  barplot(factors[,i], main=paste0('Factor ',i, ' pve= ', round(flash_get_pve(flash.model)[i],3)), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```

The first factor is the overall effect. The second factor is the effect from Yers and Salm.

Flash on loading:
```{r}
loading = flash.model$EL[, 1:5]
flash.data.l = flash_set_data(loading)
flash.model.l = flash(flash.data.l, greedy = TRUE, backfit = TRUE)
```

```{r}
factorsl = flash_get_ldf(flash.model.l)$f
row.names(factorsl) = paste0('F', seq(1:5))
pve.order = order(flash_get_pve(flash.model.l), decreasing = TRUE)

par(mfrow=c(2,2))
for(i in pve.order){
  barplot(factorsl[,i], main=paste0('Factor ',i, ' pve= ', round(flash_get_pve(flash.model.l)[i],3)), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```
<!--
```{r}
factorALL = factors %*% factorsl
factorALL = scale(factorALL, scale = sqrt(colSums(factorALL^2)), center = FALSE)
par(mfrow=c(2,2))
for(i in 1:3){
  barplot(factorALL[,i], main=paste0('Factor ',i), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```
-->

## Flash on centered Z

```{r}
Z.center = apply(mash.data$Bhat, 2, function(x) x - mean(x))
flash.data.c = flash_set_data(Z.center)
flash.model.c = flash(flash.data.c, greedy=TRUE, backfit = TRUE)
```
```{r}
factors = flash_get_ldf(flash.model.c)$f
row.names(factors) = colnames(beta_class)
pve.order = order(flash_get_pve(flash.model.c), decreasing = TRUE)

par(mfrow=c(2,3))
for(i in pve.order){
  barplot(factors[,i], main=paste0('Factor ',i, ' pve= ', round(flash_get_pve(flash.model.c)[i],3)), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```

Flash on loading:
```{r}
loading.c = flash.model.c$EL[, 1:5]
flash.data.lc = flash_set_data(loading.c)
flash.model.lc = flash(flash.data.lc, greedy = TRUE, backfit = TRUE)
```

```{r}
factorsl = flash_get_ldf(flash.model.lc)$f
row.names(factorsl) = paste0('F', seq(1:5))
pve.order = order(flash_get_pve(flash.model.lc), decreasing = TRUE)

par(mfrow=c(1,2))
for(i in pve.order){
  barplot(factorsl[,i], main=paste0('Factor ',i, ' pve= ', round(flash_get_pve(flash.model.lc)[i],3)), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```

<!--
```{r}
factorALL = factors %*% factorsl
factorALL = scale(factorALL, scale = sqrt(colSums(factorALL^2)), center = FALSE)
par(mfrow=c(1,2))
for(i in 1:2){
  barplot(factorALL[,i], main=paste0('Factor ',i), las=2, cex.names = 0.7)
}
par(mfrow=c(1,1))
```
-->

# Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
