---
title: "Home"
output:
  workflowr::wflow_site:
    toc: false
---

Application of `mash` on Blischak, John D., et al. "Mycobacterial infection induces a specific human innate immune response." Scientific reports 5 (2015).

Using John's data:

* [Expression](Expression.html)

* [Mash model - EE](Expression18_EE.html)

* [Mash model - EZ](Expression18_EZ.html)

* [EE on difference](Expression18_EE_diff.html)

* [EE on mean (joint)](Expression18_EE_john_joint.html)

* [EE on difference (joint)](Expression18_EE_john_jointdiff.html)

* [Simulation under null](Expression18_jointdiff_simulatenull.html)

------------------------------------------

We reprocess the count data.

* [Reprocess count data](Expression_reprocess18.html) We use voom+limma to fit model using data 
    
    1. at all time point. We extract time 18 summary statistics to fit mash. The result is [EE on mean (joint) using reprocessed data](Expression18_EE_reprocess_joint.Rmd)
    
    2. at time 18 only. The rersult is [EE on mean (joint) using reprocessed data](Expression18_EE_reprocess18_joint.html)

<!--
--------------------------------------------------------------

John treated the individual effect as fixed in the model. Here we processed data with individual as random effect.

# Data
1. Individual as random: [Count_IndRan](Count_IndRanBayes.html)
2. Individual as fixed: [Count_IndFix](Count_IndFixBayes.html)

We focus on the time 18 data only.

# Mash
1. Individual as random EE: [Count18_IndRan_Mash_EE](Count18_Mash_IndRanBayes_EE.html)
2. Individual as random EZ: [Count18_IndRan_Mash_EZ](Count18_Mash_IndRanBayes_EZ.html)
3. Individual as fixed EE: [Count18_IndFix_Mash_EE](Count18_Mash_IndFixBayes_EE.html)

The Shat in the data are corresponding to a t statistics. We transformed them to Shat from the z statistics. If we didn't do the transformation: [Count18_IndFix_Mash_EET](Count18_Mash_IndFixBayes_EET.html)

If we ignore the induced correlation: [Count18_IndRan_Mash_Ignore_EE](Count18_Mash_IndRanBayes_EE_Wrong.html)

# Flash
1. Flash on C: [Count18_FlashC](Count18_FlashC.html)
2. Flash on D: [Count18_FlashD](Count18_FlashD.html)
-->

